Update byrow doc.jl
sl-solution/InMemoryDatasets.jl pull request #75
Opened 2022-08-16 09:23 UTC by dyeeee

Added descriptions and examples for byrow(stdze).

2022-08-16 19:29 UTC, sl-solution commented
Please modify `byrow(ds::AbstractDataset, stdze!, cols; [threads])` to `byrow(ds::Dataset, stdze!, cols; [threads])`

Because stdze! replaces the original data set, thus, it cannot work on view of datasets.

2022-08-16 19:34 UTC, sl-solution requested changes

2022-08-16 19:34 UTC, sl-solution commented on src/byrow/doc.jl
> +─────┼────────────────────────────────────────────────
this line is not aligned - copy and paste directly from REPL to keep the original format of outputs

2022-08-17 03:47 UTC, dyeeee commented
> Please modify `byrow(ds::AbstractDataset, stdze!, cols; [threads])` to `byrow(ds::Dataset, stdze!, cols; [threads])`
> 
> Because stdze! replaces the original data set, thus, it cannot work on view of datasets.

What about other special operations with '!', Shall I change them to Dataset?

2022-08-17 07:40 UTC, sl-solution commented
> > Please modify `byrow(ds::AbstractDataset, stdze!, cols; [threads])` to `byrow(ds::Dataset, stdze!, cols; [threads])`
> > Because stdze! replaces the original data set, thus, it cannot work on view of datasets.
> 
> What about other special operations with '!', Shall I change them to Dataset?

Yes, please.  probably, I copied and pasted text and that has caused the problem.

2022-08-17 09:33 UTC, sl-solution requested changes

2022-08-17 09:33 UTC, sl-solution commented on src/byrow/doc.jl
> +    byrow(ds::Dataset, fill!, cols; [with, by = ismissing, rolling = false, threads])
please leave this as AbstractDataset, because, `byrow(fill!)` can fill view of Dataset.

2022-08-17 10:01 UTC, sl-solution approved these changes

2022-08-17 11:43 UTC, merged