Fix the issue that the maximum width of the column does not change when a format is applied to the column
sl-solution/InMemoryDatasets.jl pull request #86
Opened 2022-09-09 11:42 UTC by Kexi002

When the getmaxwidth() function calculates the maximum width of a column, the format is not applied to the column. When the user sets the format, the maximum number of columns that the Dataset can display is still calculated according to the original data. However, the maximum number of displayed columns may change after setting the format.

Now the format of each column will be applied before calculating the maximum width of the column. The maximum number of columns that can be displayed will be changed correctly.

2022-09-10 10:30 UTC, sl-solution commented
please add the `mapformats` keyword argument to `getmaxwidths`, `_show(io::IO, ::MIME"text/html", ds::AbstractDataset;...)`. Set its default value to `true`. Change your function in such a way that if `mapformats = true` then it calculates max widths based on the formatted values, otherwise, it must calculates max widths based on the actual values.

2022-09-10 20:23 UTC, sl-solution commented
Any reason for putting everything inside the `if` condition? you could simply put `if` around the 
```
f = getformat(ds, col_idx)
col = f.(col)
```
part .

2022-09-11 00:02 UTC, Kexi002 commented
> Any reason for putting everything inside the `if` condition? you could simply put `if` around the
> 
> ```
> f = getformat(ds, col_idx)
> col = f.(col)
> ```
> 
> part .

If we just put another  FOR loop inside the `if `condition, we only need to determine `mapformat` once.

But if we put `if` around the that part:
```
for (......)
  if mapformat
    f = getformat(ds, col_idx)
    col = f.(col)
  end
end
```
We need to determine `mapformat` for every columns.

2022-09-11 00:13 UTC, Kexi002 commented
I just noticed that you do the same thing with show_eltype. I thought about this question, but I'm not sure which is more important: to simplify the code or improve a little bit efficiency (which is almost negligible).

2022-09-11 10:15 UTC, sl-solution requested changes

2022-09-11 10:15 UTC, sl-solution commented on src/abstractdataset/io.jl
> +        maxwidths = getmaxwidths(ds, io, 1:mxrow, 0:-1, :X, nothing, true, buffer, 0, mapformats) .+ 2
Refer to the previous comment: `mapformats` should be a keyword argument.

2022-09-11 10:15 UTC, sl-solution commented on src/abstractdataset/io.jl
> +                      mapformats::Bool)
Here, make `mapformats` as a keyword argument with default value of `true`. Update the docstring of the function accordingly.

2022-09-12 08:42 UTC, sl-solution commented
There is a conflict ("This branch has conflicts that must be resolved"), resolve it. Current version cannot be merged.

2022-09-12 11:21 UTC, merged